### ISSUE TITLE
The transformation from rgb image to it amplitude image.

### ISSUE THREAD

**Issue by Huaifeng-xd** [Zhenxing-Dong/Fourier-inspired-neural-module#1]
Hello!Zhenxing.
Regarding the method inside the code snippet that appears to convert RGB image to its corresponding amplitude representation, do you have any source or reference for this method?I am not familiar with the underlying principle of this transformation method either, as it seems that there is no direct conversion between an RGB image and its corresponding amplitude representation. 
Thank you very much！
![image](https://github.com/Zhenxing-Dong/Fourier-inspired-neural-module/assets/50742670/36d4f485-edae-4973-88f7-347213b1939e)

**Comment by Zhenxing-Dong** [comment]
Hi! YangTian. 
Because the RGB images displayed on a normal screen are in the sRGB color space, we first need to apply gamma correction to images to adjust their intensity, and then convert their to amplitude images. More information can be referred to https://www.nature.com/articles/s41598-022-06405-2.

**Comment by Huaifeng-xd** [comment]
Thank you very much! This has been incredibly helpful to me and has resolved an urgent issue that has been troubling me for 
 quite long time.
